### ISSUE TITLE
Can I use this as a motor?

### ISSUE THREAD

**Issue by enciklinux** [YodaEmbedding/Guito-Automatic-Guitar-Tuner#1]
https://www.lazada.com.my/products/4pcs-mg996r-metal-gear-digital-torque-servo-for-futaba-jr-2c-rc-truck-motor-boat-i229947426-s297848159.html?spm=a2o4k.searchlist.list.55.242f66d4MMh3x8&search=1

**Comment by YodaEmbedding** [comment]
Probably. The [servo motor we used](https://github.com/SicariusNoctis/Guito-Automatic-Guitar-Tuner/raw/master/Hardware%20Datasheets/900-00008-Continuous-Rotation-Servo-Documentation-v2.2.pdf) had the same torque. (13 kg-cm.)

You might have to tweak the Arduino code to work with this motor's specific interface... but that goes for any motor.

**Comment by enciklinux** [comment]
Thanks for the response, Is there any way I can contact you to ask something?

**Comment by YodaEmbedding** [comment]
If it's specific to this project, I don't mind answering within this issue thread. (Or as separate issues.)

**Comment by enciklinux** [comment]
do you have skype?
