### ISSUE TITLE
Data doesnt received

### ISSUE THREAD

**Issue by enciklinux** [YodaEmbedding/Guito-Automatic-Guitar-Tuner#2]
The data doesnt received when I pluck the guitar, the frequency itself is received thru amarino and adruino but the motor doesnt moved.

When I tried to send the data at amarino monitoring option such as 0,120,90 the motor moved. It seems the message to send doesnt make the motor move

**Comment by YodaEmbedding** [comment]
You might need to modify the code in [`Motor.cpp`](https://github.com/SicariusNoctis/Guito-Automatic-Guitar-Tuner/blob/master/GuitoArduino/Motor.cpp) to work with your specific motor.

Try modifying the `rotateMotor()` function until you can get the motor moving. Calling, e.g. `rotateMotor(100)` *should* result in the motor spinning at 100% power.
